# Name
name: Adrian DC

# Description
description: Developments

# Markdown
kramdown:
  parse_block_html: true
  show_warnings: true

# Gems
gems:
  - jekyll-sitemap

# Exclusions
exclude:
  - CREDITS.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

# Pages
menu:
  - index.md
  - developments.md
  - about.md
